version: 0.2

phases:
  install:
	nodejs: 18
     commands:
	 - echo "Installing dependencies..."
	 - npm ci
	 - npx playwright install --with-deps
  
build:
    commands:
	- echo "Running Playwright tests..."
	- npx playwright test
artifacts:
  files:
    - 'playwright-report/**'
discard-paths: no
